# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
main:
  # - name: Demo
  #   url: '#about'
  #   weight: 10
  - name: Posts
    url: '#posts'
    weight: 10
  - name: Gospels 
    url: commentary/gospels/
    weight: 30
  - name: Revelation 
    url: commentary/revelation/
    weight: 20
  - name: Revelation Videos
    url: commentary/revelation/rev-av/
    weight: 25
  - name: Learn Hebrew
    url: '#courses'
    weight: 60
  - name: Israel Tour 2023
    url: tour/
    weight: 70
  # - name: Bible Portions
  #   url: portions/
  #   weight: 80
 # - name: Contact
  #   url: '#contact'
  #   weight: 70
